# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4a03273beb245389dbfbfd6c9a76e9adc1e48a4b7bc2efeaa91bc4d1396baf50f70d3abaa7aabad92af2649f041853890841e61b0d3f3932bb4a16ba92f86d1

test:
  secret_key_base: aadb8e9627aab23f2f62b45430f69674bab1fd7ff873d95e242acd0d62c3708f4ce6b40386c58740f75105850efd26f5585a889114fd5f60193a91d8bb605a32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
